### PR TITLE
Fix Watchify failure to reload(?)

### PR DESCRIPTION
**Pull request by Anoninnyc**
### What github.com/wevote/WebApp/issues does this fix?
#757 
### Changes included this pull request?
Minor change to Gulpfile

### CODE REVIEW

**Comment by Anoninnyc** [comment]
@DaleMcGrew Let me know if this works on your machine.

Thx, 
Chris

**Comment by josephevans** [comment]
Doesn't this change undo my fix for NOT using watchify on production?? See PR 758.

**Comment by Anoninnyc** [comment]
@josephevans  Yes, it does. I was unaware of your PR all together. I'll remove it shortly.

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc I tested this locally and with polling, browserify doesn't run when I make changes. I am going to close this pull request given the inclusion of the index.html changes that are in another pull request.

**Pull request closed without merging**
