### PR TITLE
Fix close button on PaidAccountUpgradeModal and update mobile view fo…

### PR DESCRIPTION
**Pull request by jarodpeachey**
…r the add endorsements page

### What github.com/wevote/WebApp/issues does this fix?
#2491 #2493 
### Changes included this pull request?
I removed the media query hiding the close button on mobile, and I also updated the add endorsements page for a better view on mobile.

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, thank you for these changes! 👍  I am approving this pull request, but could you please explore combining `WrapperFullWidth` and `Wrapper` in FilterBase into a single style (where we define the styles at the bottom of the page) so that the `WrapperFullWidth` styles are used on mobile, and `Wrapper` styles are used in tablet and desktop, using width breakpoints? I don't want to have to declare two copies of FilterBase to accomplish Responsiveness.

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, I got a chance to look more closely, and since `Wrapper` and `WrapperFullWidth` in FilterBase only have one very simple difference, you would want to use only one styled component, and pass in a variable. (An example is line 52 in this file: WebApp/src/js/components/Welcome/Section.jsx ) Doing major switch statements that duplicate lines of code (like you have with `this.props.fullWidth`) is something we should avoid whenever possible. Would you be willing to refactor your change to use `this.props.fullWidth` as a variable in `Wrapper`, and remove the major switch statement?

**Comment by jarodpeachey** [comment]
Hey @DaleMcGrew ,
Just submitted these fixes. 

I know that in the past I’ve used switch statements incorrectly like that, so would you like me to go through and use this new method to reduce the number of lines of code in other files?

**Comment by DaleMcGrew** [comment]
Hi Jarod, you are always welcome to re-factor as you feel inspired, but since we have so much new work to do, I would hold off on putting too much time into re-factoring at this point.

**Pull request merged**
