### PR TITLE
#65 adding jsx to the linting

### PR DESCRIPTION
**Pull request by pertrai1**
NOTE: a lot of errors so you will have to pass `-n` to your commit message to get past the commit hook stopping the commit. There are close to 150 errors now with adding .jsx files. `mock-data` folder being excluded now

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
I am handing out jerseys for Little League this morning, but should be able to take on some of the cleanup work late this afternoon Pacific time.

**Comment by pertrai1** [comment]
I am not available until later on this afternoon as well. Will look at the errors and make fixes as well.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1, I notice that in this pull request you remove a number of the comments that start with "VISUAL DESIGN HERE". The link to the mockup is very helpful to me when I'm building out and iterating on a page. What are your thoughts?

**Comment by pertrai1** [comment]
@DaleMcGrew I think that it is important that we have an issue that can always reference a pull request and it is in the issue that there is either a link to the artifacts, or a link to a wiki page that can be created for the artifacts for that particular module. Does that sound like a reasonable plan?

**Comment by DaleMcGrew** [comment]
I'm open to talking about that. I like the improvements to our procedures that we are looking at. Until we have a chance to talk about it and transition, I don't want to lose comments in the code. I will add the "VISUAL DESIGN HERE" links back to the code for now until we get a chance to talk about migrating to a better system for linking to designs.

**Comment by pertrai1** [comment]
@DaleMcGrew Ok, please let others know that is code comments are needed to stay in the code, have some reference so they are not removed, i.e - KEEP, NO REMOVE, etc.

**Pull request merged**
