### PR TITLE
Candidate page additions

### PR DESCRIPTION
**Pull request by lisamcho**
Candidate page changes:
-fetches office name, list of positions.
For each position, fetches the details of that position.

Changed all other components as needed to remove warnings "setState on unmounted components"

Removed redirecting from candidate page back to ballot if candidate is not loaded, now loads all needed candidate data so you can load a candidate page directly. Or you can load the ballot then navigate to candidate page.

Still breaking: navigating back to the ballot from the candidate page.

### CODE REVIEW

**Comment by nf071590** [comment]
Hey @lisamcho I noticed that a fix in service.js is overlapping with the build fix that I confronted. A pull request from upstream would help resolve the on on line *50* (i think..) If you need help resolving any lint errors message me on slack channel.

**Comment by lisamcho** [comment]
@nf071590 removed change to service.js.

**Comment by nf071590** [comment]
@lisamcho I can't understand what's happening in that request and it's still failing the build. Let me know if you need help with anything.

**Comment by lisamcho** [comment]
Hey are you on slack?

**Comment by nf071590** [comment]
I will get on now..

**Comment by nf071590** [comment]
Lisa, run 

 npm test

from command line to check build success/fail.

Best,

Nick

**Comment by pertrai1** [comment]
:+1:

**Pull request merged**
