### PR TITLE
Fixed some eslint errors from running "npm test". Added Twitter Description to organization display.

### PR DESCRIPTION
**Pull request by DaleMcGrew**
Takes advantage of the new twitter description field made available in the voterGuides and organization API endpoints. Cleaned up quite a few eslint errors.

### CODE REVIEW

**Comment by lisamcho** [comment]
Nice work with the lint errors. Would recommend refactoring the twitter description string parsing to avoid duplicating the code multiple places.

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho, Where would I put a JavaScript function we want to use multiple places? (I.e. What file)

**Comment by lisamcho** [comment]
I'd put it into in the utils folder. Maybe also the function used to parse/format twitter followers with commas. @DaleMcGrew

**Comment by DaleMcGrew** [comment]
Thanks. My preference would be that you approve this pull request, and then I will refactor in my next pull request.

**Comment by lisamcho** [comment]
@DaleMcGrew I also get "bundle.js:58334 Uncaught TypeError: Cannot read property 'toString' of null" when running your code.

**Comment by DaleMcGrew** [comment]
@lisamcho I added fixes to the problems you pointed out. Ready for another review.

**Comment by lisamcho** [comment]
Looks good! 👍

**Pull request merged**
