### PR TITLE
Add formatting utils and format date on positionitem view

### PR DESCRIPTION
**Pull request by lisamcho**
Enabled showing "Today" + time if it is today, otherwise generic date string.

### CODE REVIEW

**Comment by lisamcho** [comment]
Please hold off on review. Did not see further instructions to format per Yesterday at 3:15PM OR 2 days ago OR 6 months ago.

**Comment by DaleMcGrew** [comment]
Thanks Lisa. Today + time is a great start.

**Comment by lisamcho** [comment]
@DaleMcGrew @pertrai1 Ready for review. Must run npm install again as I used this: http://momentjs.com/

**Comment by DaleMcGrew** [comment]
github is complaining "This branch has conflicts that must be resolved". I'm looking forward to learning how to resolve conflicts like this.

**Comment by lisamcho** [comment]
Hmmm, I pulled down develop master and merged it to resolve the merge conflicts, but now I can't create a commit with the merges in it. I get the following errors. The code browserifies and runs fine on local, so I'm not sure what the errors mean. Anyone can help me to resolve it?: 

pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:

Also I rerun 'npm test' and rather than linting syntax it gives me:
babel-node tests/*.js | faucet

sh: babel-node: command not found
sh: faucet: command not found
npm ERR! Test failed.  See above for more details.

**Comment by pertrai1** [comment]
@lisamcho Hey run `npm install -g babel tape faucet browserify browser-run` and see if your test will run and pass. I am not on a computer that will allow me to pull and see if there is anything that can be cherry picked to make sure merge will resolve.

**Comment by pertrai1** [comment]
@lisamcho Also, still in your branch you can do this to squash your commits into one commit:

`git rebase -i HEAD~2`

This will show you the last 2 commits with the work `pick`, the sha # and the commit message.
Take the last commit and change `pick` to `squash` and then save.
This will then put you into another interactive mode where you can pick what commit message you want to use. The one you don't want to use you can put a `#` in front of and either keep the commit message you have chosen or take that message and change it.

If you feel that it is not going right, you can do `git rebase --abort` and it will stop and we can get together on it.

**Comment by DaleMcGrew** [comment]
@pertrai1 I think there is a glitch with the precommit code because I tried to make the same changes and check in, and I got the same error. Can I delete the "pre-commit" line "test" for now?:
Error:Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/dalemcgrew/PythonProjects/webapp/node_modules/pre-commit/node_modules/spawn-sync/error.log for more details
sh: babel-node: command not found
sh: faucet: command not found
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit:

**Comment by pertrai1** [comment]
@lisamcho and @DaleMcGrew Please go ahead and take out the test for now until I get it squared away. Might not have been good to add at 2:00 am in the morning.

**Comment by DaleMcGrew** [comment]
Thanks @pertrai1. @lisamcho, I tried a couple of things and kept running into pre-commit problems. I would recommend working locally and hold off trying to check in until Rob (or Nick) can take a look. I get the same errors when I run "npm test" before trying to check in:
------------------
(WebAppEnv)dalemcgrew:WebApp dalemcgrew$ npm test

> wevoteusa@0.2.0 test /Users/dalemcgrew/PythonProjects/webapp
> babel-node tests/*.js | faucet

sh: babel-node: command not found
sh: faucet: command not found
npm ERR! Test failed.

**Comment by pertrai1** [comment]
@DaleMcGrew can you run `npm install -g babel-node faucet` and then run the test and see what happens

**Comment by DaleMcGrew** [comment]
These errors:
===============
(WebAppEnv)dalemcgrew:WebApp dalemcgrew$ npm install -g babel-node faucet
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/dalemcgrew/NodeEnvironments/WebAppEnv/bin/node" "/Users/DaleMcGrew/NodeEnvironments/WebAppEnv/bin/npm" "install" "-g" "babel-node" "faucet"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/babel-node
npm ERR! 404 
npm ERR! 404 'babel-node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dalemcgrew/PythonProjects/webapp/npm-debug.log

Please let me know if you think you need the npm-debug.log

**Comment by lisamcho** [comment]
OK, I got around the precommit hooks and rolled these changes up with other updates to candidate page. Can close this pull request.

**Pull request closed without merging**
