### PR TITLE
Add loading screen

### PR DESCRIPTION
**Pull request by lisamcho**
Add a basic loading page that shows up before the javascript is loaded. 
Just put a blue page with "WeVote" on it for now. This could definitely use a designer's touch. @ixley

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
👍

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho I don't understand this splash screen. It loads and then is removed yet I still have the spinner waiting for the candidates to load. Is that the expected behavior?

**Comment by lisamcho** [comment]
Wasn't sure, we could change this to wait for the candidates loaded to
elminate the spinner entirely.

**Comment by pertrai1** [comment]
I do agree but I am just trying to wrap my head around looking at what looks like some what of a "coming soon" splash page, and if it takes more than 5 seconds for something to happen, I might leave. Could you add something like "Loading app...." ??

**Pull request merged**
