### PR TITLE
Uncomment YAML, .gitignore, and Lint

### PR DESCRIPTION
**Pull request by Anoninnyc**
### What github.com/wevote/WebApp/issues does this fix?
None
### Changes included this pull request?
Uncomment YAML, update .gitignore, and Linting to tests

### CODE REVIEW

**Comment by Anoninnyc** [comment]
@DaleMcGrew The segment of the original .travis,yml file I commented out seems to throw a Travis parse error

**Comment by Anoninnyc** [comment]
@DaleMcGrew Also, take a look @ [this](https://travis-ci.org/wevote/WebApp/jobs/213056400) link to see what Travis is doing.

**Comment by DaleMcGrew** [comment]
👍

**Comment by Anoninnyc** [comment]
@DaleMcGrew  :D

**Pull request merged**
