### PR TITLE
Instant Search Display Fixes

### PR DESCRIPTION
**Pull request by pertrai1**
This fix changes the position of the search results box for all
of the different media queies. It also adds the absolute position of the
dropdown results that will allow the header to stay in place and not
move down.

This does not handle the case of clicking on a link and having the
results dissapear. I am not knowledgable enough about Link to know how
to make that change at this time. It also does not take into account the
blue button being white. That is a Bootstrap icon and would need some
consideration.

Please pull from my repo this branch and test locally to see how it
works currently.

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
@pertrai1 Thank you Rob, I'm taking a look now.

**Comment by pertrai1** [comment]
@DaleMcGrew Great. If you don't have anyone who knows a great deal about the Router Link, I can look more into that and see how some type of `onClick` can be used to have the `search-container` be removed.

**Comment by pertrai1** [comment]
@DaleMcGrew when you get a chance pull again and see changes locally.

**Comment by pertrai1** [comment]
@DaleMcGrew Updates to to-do's have been added to #328

**Comment by DaleMcGrew** [comment]
👍

**Pull request merged**
