### PR TITLE
update SearchBar into SearchBar2024

### PR DESCRIPTION
**Pull request by ivanko22**
### What github.com/wevote/WebApp/issues does this fix?

- Implement updates on the Search Bar, renaming it to SearchBar2024 
- Ensure all references to the SearchBar within the web app are transitioned to SearchBar2024

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
Hi @ivanko22 thank you for this update to the pull request. You are moving in the right direction. The idea behind creating a new SearchBar2024 component is so we could leave the SearchBar component in place as-is most places in the code, and test SearchBar2024 (and the new lower-level component you created from Storybook) in different contexts.

I would ask that you leave this component unchanged: src/js/components/Search/SearchBar.jsx

...and then create a new component src/js/components/Search/SearchBar2024.jsx that includes your new Storybook search input.

Note: SearchBar and SearchBar2024 should be interchangeable, so we can compare the two.

**Comment by ivanko22** [comment]
Hi @DaleMcGrew I change back files with SearchBar and keep SearchBar2024 in Campaign and OneValue.

**Comment by ivanko22** [comment]
@DaleMcGrew 
Storybook with SearchBar: 
https://6577876dff6fd9ff88b500fa-mgpvvlkbez.chromatic.com/?path=/story/design-system-inputs--searchbox
Chromatic with SearchBar: 
https://www.chromatic.com/build?appId=6577876dff6fd9ff88b500fa&number=19

**Comment by DaleMcGrew** [comment]
Great work @ivanko22! Thank you. 👍

**Pull request merged**
