### PR TITLE
TestAutomation for WV544

### PR DESCRIPTION
**Pull request by shan14T**
WhosRunningForOffice Navigation links test cases:

### What github.com/wevote/WebApp/issues does this fix?
wv544 

### Changes included this pull request?
Added spec file 'WhosRunningForOffice.js' in wdio config
Added the script file WhosRunningForOffice.js
Added the data file 'populateStateAndCandidateData.js'

### CODE REVIEW

**Comment by fdiazq** [comment]
@shan14T Could you remove the comment from the config file on the test pages

**Review by fdiazq — CHANGES_REQUESTED** [review]
@shan14T

**Comment by shan14T** [comment]
I removed the comment. thanks

**Review by fdiazq — APPROVED** [review]
@shan14T 👍

**Pull request merged**
