### PR TITLE
Implement the React Burger Menu

### PR DESCRIPTION
**Pull request by pertrai1**
This is for the mobile hamburger so then the icon will open and close the mobile menu.

Issue #124

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
Awesome! 👍

**Comment by DaleMcGrew** [comment]
Hi Rob, clicking the hamburger isn't closing the menu. Can you please take a look? Here is an image of what I am seeing.
screen shot 2016-05-14 at 11 05 10 am

**Comment by pertrai1** [comment]
@DaleMcGrew Did you do an `npm install`? If so, are there any errors in the console?

**Comment by pertrai1** [comment]
@DaleMcGrew I just pulled latest on my macbook air and did the `npm install`, ran `gulp` and then was able to open and close hamburger using Chrome and Safari. Do not have Firefox on this machine.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 I ran npm install a second time, then gulp and it picked up the change this time. Thank you! Next time I will try running npm install twice before complaining. :-)

**Comment by pertrai1** [comment]
@DaleMcGrew  :-) - always remember that three times a charm so you should run it one more time. Lol. Glad that it is work

**Pull request merged**
