### PR TITLE
Refactored Sign in Verification modal for email and phone numbers to fix several bugs. Sign in with email and phone needs more testing in Cordova. Improvements for private labeling. Fixed bug with friend requests layout.

### PR DESCRIPTION
**Pull request by DaleMcGrew**
Refactored Sign in Verification modal for email and phone numbers to fix several bugs. Sign in with email and phone needs more testing in Cordova. Improvements for private labeling. Fixed bug with friend requests layout.

### CODE REVIEW

**Comment by SailingSteve** [comment]
@DaleMcGrew 
What bug were you fixing, by moving clearEmailAddressStatus() and clearSecretCodeVerificationStatus() back out of VoterStore and back into VoterActions?  (Reverting what I had just done in the previous commit to these files).  This broke Cordova again with the same "Cannot dispatch in the middle of a dispatch" error. This prevents sign in with email.

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve this was one of the topics we discussed in a phone call about two months ago. Clearing data in the VoterStore directly was causing problems by not triggering necessary VoterStore listeners in a couple of components who need to know when the VoterStore changes. I refactored the two VoterActions calls into a single one, either `clearSecretCodeVerificationStatusAndEmail` for email or `clearSecretCodeVerificationStatusAndPhone` for phone so there should only be a single dispatch. Which file is "Cannot dispatch in the middle of a dispatch" coming from in Cordova now? 
If it is from WebApp/src/js/components/Settings/SettingsVerifySecretCode.jsx around line 68, it could make sense to use an `isCordova` switch to prevent the error for now until we can discuss.

**Comment by SailingSteve** [comment]
The one for phone #s seems to work, the one for email fails.

Uncaught Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (https://localhost/bundle.js:237487:15)
    at Dispatcher.dispatch (https://localhost/bundle.js:238084:37)
    **at Object.clearSecretCodeVerificationStatusAndEmail (https://localhost/bundle.js:81839:75)**
    at VoterEmailAddressEntry.<anonymous> (https://localhost/bundle.js:146624:78)
    at callCallback (https://localhost/bundle.js:269603:12)
    at commitUpdateQueue (https://localhost/bundle.js:269624:9)
    at commitLifeCycles (https://localhost/bundle.js:277989:11)
    at commitLayoutEffects (https://localhost/bundle.js:280706:7)
    at HTMLUnknownElement.callCallback (https://localhost/bundle.js:261230:14)
    at Object.invokeGuardedCallbackDev (https://localhost/bundle.js:261279:16)
invariant @ bundle.js:237487
dispatch @ bundle.js:238084
clearSecretCodeVerificationStatusAndEmail @ bundle.js:81839
(anonymous) @ bundle.js:146624
callCallback @ bundle.js:269603
commitUpdateQueue @ bundle.js:269624
commitLifeCycles @ bundle.js:277989
commitLayoutEffects @ bundle.js:280706
callCallback @ bundle.js:261230
invokeGuardedCallbackDev @ bundle.js:261279
invokeGuardedCallback @ bundle.js:261341
commitRootImpl @ bundle.js:280431
unstable_runWithPriority @ bundle.js:311157
runWithPriority$1 @ bundle.js:268561
commitRoot @ bundle.js:280270
performSyncWorkOnRoot @ bundle.js:279609
(anonymous) @ bundle.js:268612
unstable_runWithPriority @ bundle.js:311157
runWithPriority$1 @ bundle.js:268561
flushSyncCallbackQueueImpl @ bundle.js:268607
flushSyncCallbackQueue @ bundle.js:268594
scheduleUpdateOnFiber @ bundle.js:279173
enqueueSetState @ bundle.js:269752
Component.setState @ bundle.js:305875
onVoterStoreChange @ bundle.js:146826
__emitToSubscription @ bundle.js:237161
emit @ bundle.js:237141
__invokeOnDispatch @ bundle.js:238870
(anonymous) @ bundle.js:238937
_invokeCallback @ bundle.js:238119
dispatch @ bundle.js:238094
success @ bundle.js:86004
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
innerAjax @ bundle.js:227829
$ajax @ bundle.js:227834
Dispatcher.loadEndpoint @ bundle.js:85998
voterVerifySecretCode @ bundle.js:82260
SettingsVerifySecretCode._this.voterVerifySecretCode @ bundle.js:143783
handleKeyDown6 @ bundle.js:143971
callCallback @ bundle.js:261230
invokeGuardedCallbackDev @ bundle.js:261279
invokeGuardedCallback @ bundle.js:261341
invokeGuardedCallbackAndCatchFirstError @ bundle.js:261355
executeDispatch @ bundle.js:265528
processDispatchQueueItemsInOrder @ bundle.js:265560
processDispatchQueue @ bundle.js:265573
dispatchEventsForPlugins @ bundle.js:265584
(anonymous) @ bundle.js:265793
batchedEventUpdates$1 @ bundle.js:279676
batchedEventUpdates @ bundle.js:261030
dispatchEventForPluginEventSystem @ bundle.js:265792
attemptToDispatchEvent @ bundle.js:263290
dispatchEvent @ bundle.js:263209
unstable_runWithPriority @ bundle.js:311157
runWithPriority$1 @ bundle.js:268561
discreteUpdates$1 @ bundle.js:279693
discreteUpdates @ bundle.js:261041
dispatchDiscreteEvent @ bundle.js:263174
Show 6 more frames

**Comment by SailingSteve** [comment]
What were the other components that did not update?  It seems that if you change the state of the store, the listener should trigger.

**Comment by DaleMcGrew** [comment]
@SailingSteve: I am able to reproduce the problem now, and I'm working to get rid of "Cannot dispatch in the middle of a dispatch". I won't check in changed code -- I'll just tell you what I find.

**Comment by DaleMcGrew** [comment]
I found a fix, and emailed you details to your @WeVote.US email address.

**Pull request merged**
