### PR TITLE
[Issue #1695] Fix display issues in iframe

### PR DESCRIPTION
**Pull request by lazorfuzz**
### What github.com/wevote/WebApp/issues does this fix?
Issue [#1695]

### Changes included this pull request?
Changed iframeResizer options for height detection.
Commented out some CSS that was making cards go underneath the nav bar in the iframe view.

### CODE REVIEW

**Comment by lazorfuzz** [comment]
Resolved merge conflict in package-lock.json

**Comment by lazorfuzz** [comment]
Fixed isFriendsOnly destructuring error

`let { isFriendsOnly } = this.props.isFriendsOnly;` should be `let { isFriendsOnly } = this.props;`

**Comment by DaleMcGrew** [comment]
Thank you @lazorfuzz. 👍

**Comment by lazorfuzz** [comment]
Hi @DaleMcGrew, should we also merge the changes to CodeCopier.jsx and WeVoteBallotEmbed.jsx? The iframeResizer library needs the additional `heightCalculationMethod: 'max'` option to avoid the cutoff at the bottom of the page.

**Comment by DaleMcGrew** [comment]
Yes please @lazorfuzz -- good catch. (re: merge the changes to CodeCopier.jsx and WeVoteBallotEmbed.jsx)

**Pull request merged**
