### PR TITLE
Fix to layout of SignInModal when Virtual Keyboard is displayed.

### PR DESCRIPTION
**Pull request by SailingSteve**

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
👍

**Comment by DaleMcGrew** [comment]
On testing, I found that when I click in the email or phone box, the modal shifts to the left, mostly off screen. Prior to this pull request it was shifting mostly off screen to the right.

**Comment by SailingSteve** [comment]
Is the code on the live server now?

**Comment by SailingSteve** [comment]
Those two modals work fine on a phone, but not in the Chrome devtools simulator.
The sign in modal is too high on the phone, but looked good when I checked it in.
I'll take a look tomorrow.

**Pull request merged**
