### PR TITLE
Start work on profile picture cards

### PR DESCRIPTION
**Pull request by jarodpeachey**

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
How exciting to see this work underway @jarodpeachey! Am I correct that I should leave this pull request in place for you to continue to work on it, or would you say that it is ready to start integrating with the API server?

**Comment by jarodpeachey** [comment]
It depends what you think should be done first. If you want, I can continue to work on this and add the upload functionality. If not, you can hook it up to the API and I can do that later.

**Comment by DaleMcGrew** [comment]
When you say that you can add the upload functionality, are you talking about one of these notes?
```
NOTE 2: Given time (not part of this issue), I would like us to find a package that allows drag-and-drop upload of a photo on Desktop
NOTE 3: Given time (not part of this issue), I would like to find a react tool that lets us crop and resize photos before we submit them to the API server.
```

Or this level of upload?
```
We have code that lets you upload a photo on the "Logo & Sharing" page -- there is good example code there:
http://localhost:3000/settings/sharing
See: src/js/components/Settings/SettingsSharing.jsx
```

**Comment by jarodpeachey** [comment]
I might as well start right away with the drag and drop if you want

**Comment by DaleMcGrew** [comment]
Drag and drop would be phenomenal, thank you!

**Comment by jarodpeachey** [comment]
@DaleMcGrew I've added the drag and drop support to this, all that's left is to download the image and upload it to the API

**Comment by DaleMcGrew** [comment]
That is excellent @jarodpeachey. I'll review this and start working on the API side. Great work!

**Comment by DaleMcGrew** [comment]
👍 Great work @jarodpeachey.

**Pull request merged**
