### PR TITLE
Restructured Documentation for Better Usability

### PR DESCRIPTION
**Pull request by DaleMcGrew**
Restructured our documentation so it is easier for new developers to get started, and easier for current developers to zero-in on the specific information they need. I tried *really* hard to make sure I didn't delete any existing documentation. My apologies in advance if I removed any documentation (without moving it to a new place). There is still more clean-up of this documentation to be done, but I think it can be done incrementally, and by multiple people. 

PS. Can someone help create the table of contents for these pages with doctoc?

### CODE REVIEW

**Comment by pertrai1** [comment]
@DaleMcGrew : try to run `npm run build:doc` and see if that builds it for you.

**Comment by pertrai1** [comment]
FYI: I will be on slack and hangout shortly if you need help

**Comment by pertrai1** [comment]
@DaleMcGrew Did you have this in your markdown files at the top?

```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->

<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

**Comment by DaleMcGrew** [comment]
I didn't remove the doctoc comments if they were already in files, but I haven't added it to the new files yet. I can add it on the next iteration.

**Comment by pertrai1** [comment]
@DaleMcGrew How about we merge in and then I can view as I run the doctocs. I need to update changelog with the newest tag of commits.

**Pull request merged**
