### PR TITLE
Fix error in console from withStyles() export on location guess

### PR DESCRIPTION
**Pull request by jarodpeachey**
### Changes included this pull request?
Fixed the error in the console from incorrect export of component with styles.

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
👍

**Comment by lazorfuzz** [comment]
@DaleMcGrew @jarodpeachey @uroshima this is still incorrect. Because in the Location component we are not using any Material theme properties or style overrides, neither withTheme nor withStyles are needed.

`export default Location;` will work just fine.

In the future, if we are using Material theme variables or style overrides, then the proper way to export is as follows: `export default withTheme()(withStyles(styles)(ComponentName));`.

Please take a look at `components/Ballot/BallotSearch.jsx` for a proper example on using Material theme and style overrides, and how components using them should be exported.

**Comment by jarodpeachey** [comment]
Thanks for the tip, @lazorfuzz.  I just checked out the BallotSearch.jsx file to get the proper way to do it.  I'll make sure to use that method next time.

Just to double-check, should I edit the location guess file to use `export default LocationGuess;`?

**Comment by lazorfuzz** [comment]
@jarodpeachey No worries, I'm refactoring the component now, and I'll include that change. It turns out withStyles is actually needed because there was some styling done for the Material Place icon. It was done with inline styles, but I'm changing it to style overrides because we want to avoid inline styles like the plague.

**Comment by uroshima** [comment]
Thanks @lazorfuzz, I'll make sure to use that method next time.

**Pull request merged**
