### PR TITLE
Add redirects for empty ballot and empty following list

### PR DESCRIPTION
**Pull request by lisamcho**
Redirects to More Organizations page when list of organizations user is following is empty.
Redirects to Address page when Ballot is empty.

### CODE REVIEW

**Comment by pertrai1** [comment]
@lisamcho If you know how, can you squash these commits into 1? If not, I will go ahead and :+1: and merge. If you do `git rebase -i` and squash all but the last one, you can then change your commit message to what you want it to be and do a `git push -f`.

**Comment by lisamcho** [comment]
@pertrai1 @DaleMcGrew  With strict equality, ready for review

**Comment by pertrai1** [comment]
Also, if you are not comfortable with the squash, I will clone from your own repo, squash, and then pull request back to your repo to update your pull request here

**Comment by lisamcho** [comment]
@pertrai1, If you want to squash, please go ahead, because I'm not that great/comfortable at workflows other than branch, commit, push. Maybe on Saturday I can pick your brain on squashing commits?

**Comment by pertrai1** [comment]
@lisamcho sounds good. I will get your repo branch and squash for you and then push back the commit. One moment

**Pull request merged**
