### PR TITLE
Translate SettingsMenuMobile to use camel case.

### PR DESCRIPTION
**Pull request by Tezaen**
### What github.com/wevote/WebApp/issues does this fix?
#1850

### Changes included this pull request?
Convert routes/Settings/SettingsMenuMobile.jsx to use camel case.

### CODE REVIEW

**Comment by utsab** [comment]
@DaleMcGrew, we were not sure about the meaning of voter.linked_organization_we_vote_id.    Does this mean that a user's account is somehow linked to a specific organization?  What part of the UI would allow us to set voter.linked_organization_we_vote_id?

**Comment by DaleMcGrew** [comment]
👍 Thank you @Tezaen for your first pull request to We Vote! These changes look great. 

@utsab, to answer your question: voter.linked_organization_we_vote_id is how we link a voter to an organization. Every voter has an organization object in case they want to push any of their opinions public. All publicly visible opinions must be attached to an organization object.

**Comment by utsab** [comment]
@DaleMcGrew, thanks for explaining that.  Where would I go in the website to link myself to an organization? I went to the Settings page, but I wasn't sure where to go from there.

**Comment by DaleMcGrew** [comment]
Hi @utsab, this is unfortunately a file we can only test on our Cordova app, so there is nothing more to test here.

**Pull request merged**
