### PR TITLE
Opinions

### PR DESCRIPTION
**Pull request by nf071590**
Fixing build issues for all the visual comment blocks that were added to different files

### CODE REVIEW

**Comment by nf071590** [comment]
@pertrai1 yeah Rob I need to figure out how to rebase properly, it's really confusing right now but I think I'll get the hang of it eventually here...

**Comment by nf071590** [comment]
The issues we're from adding:
`{/* Visual Design Here: .... */}`

The outer `{  }` curly braces are redundant

**Comment by DaleMcGrew** [comment]
Ah, good to know -- thank you. -Dale

**Comment by nf071590** [comment]
Commenting in JS: http://www.w3schools.com/js/js_comments.asp

**Comment by DaleMcGrew** [comment]
So /* normal javascript comments */ and {/* comments within react blocks */}

**Comment by nf071590** [comment]
@DaleMcGrew JSX comments have different syntax and yeah they would go in enclosing curly braces...  http://wesbos.com/react-jsx-comments/

**Comment by DaleMcGrew** [comment]
@pertrai1 when you get time could you approve this (no massive rush)? I need to increase my skills with git so I can help out with reviewing big commits like this.

**Comment by pertrai1** [comment]
:1

**Comment by pertrai1** [comment]
:+1:

**Comment by pertrai1** [comment]
@nf071590 merged my man

**Comment by nf071590** [comment]
My man!

**Pull request merged**
