### PR TITLE
Rewire candidate and ballot without support items

### PR DESCRIPTION
**Pull request by lisamcho**
All support items (# of support and oppose) and user actions to support or oppose don't work.
Ballot loads and Candidate pages load.

There is hardwiring as a stub for PositionsForBallotItem and StarActions (since API will soon be changed to return we_vote_id), code just returns the id for BernieSanders, hence only Bernie has positions showing.

### CODE REVIEW

**Comment by pertrai1** [comment]
@lisamcho Pull @nf071590 latest changes and see where the conflicts reside and resolve. I just merged Nick's changes that would be in conflict with your commit

**Comment by DaleMcGrew** [comment]
Hi Lisa, I just updated the endpoints on the live server that are checked in this issue: https://github.com/wevote/WeVoteServer/issues/87

**Comment by DaleMcGrew** [comment]
Hi @lisamcho, would you be able to resubmit this pull request, now that the end points you need are supported?

**Comment by lisamcho** [comment]
Yes, will do, Thanks!

**Comment by lisamcho** [comment]
Closing this pull request

**Pull request closed without merging**
