### PR TITLE
Validate Emails

### PR DESCRIPTION
**Pull request by Anoninnyc**
### What github.com/wevote/WebApp/issues does this fix?
#747 
### Changes included this pull request?
Only show message option if *at least* 1 email address is valid

### CODE REVIEW

**Comment by Anoninnyc** [comment]
@DaleMcGrew The Saucelabs portion of the build failed- though this works on my end. 
It looks easily remediable here is error message I'm pulling from Travis logs:
**sample: Failed {"message":"[elementByCss(\"button.btn.btn-success\")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters.**

**Comment by Anoninnyc** [comment]
note to self: extract extra functionality or use || statements.

**Comment by Anoninnyc** [comment]
@DaleMcGrew  Let me know what you think.

**Comment by DaleMcGrew** [comment]
This looks great @Anoninnyc -- thank you for the updates.

**Pull request merged**
