### PR TITLE
removing module.exports and require in favor of es6 export and import

### PR DESCRIPTION
**Pull request by chulinguy**
### What github.com/wevote/WebApp/issues does this fix?
Github issue: #1227

### Changes included this pull request?
just changing "require" to "import" and "module.exports" to "export default"

### CODE REVIEW

**Comment by pertrai1** [comment]
👍

**Comment by DaleMcGrew** [comment]
Thank you for doing the code review @pertrai1, and thank you @chulinguy for doing this pull request. The automated test threw these errors. @chulinguy can you please take a look? You can run "npm test" from the command line to see the error too:

/home/travis/build/wevote/WebApp/src/js/dispatcher/Dispatcher.js
  24:16  error  Parsing error: Unexpected token
  22 | };
  23 | 
> 24 | export default = new Dispatcher();
     |                ^
  25 | 
/home/travis/build/wevote/WebApp/src/js/dispatcher/RequestDispatcher.js
  40:16  error  Parsing error: Unexpected token
  38 | });
  39 | 
> 40 | export default = Dispatcher;
     |                ^

**Comment by chulinguy** [comment]
oops sorry I forgot to add the latest commit ... updating my PR

**Comment by DaleMcGrew** [comment]
Thank you!

**Pull request merged**
