### PR TITLE
Check for reload ballot

### PR DESCRIPTION
**Pull request by lisamcho**
If you save an address and no Google Civic Election is found, display a message page explaining why the ballot is empty.
If you save a different address with a Google Civic Election found ,refresh the ballot.
This commit also fixes the issues with navigating to Candidate Page and refreshing, then navigating back to Ballot (it initiates BallotStore.initialize) from the CandidatePage (kinda hacky, but ok for first version, to refactor later?)
Also, change the hard redirect to soft redirect within React.

### CODE REVIEW

**Comment by lisamcho** [comment]
@nf071590 @DaleMcGrew

**Comment by pertrai1** [comment]
@lisamcho @DaleMcGrew There was some code review that was needed for this pull request. It was nothing earth shattering.

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho @nf071590 There was a merge of this without any code review thumbs up. Was there a code review for this that was not recorded here?

**Comment by DaleMcGrew** [comment]
I look forward to discussing code reviews and committing process after we hit Version 1.0. Until we achieve Version 1.0, we have not agreed to require thumbs up before approving pull requests. https://github.com/wevote/WebApp/issues/28

**Comment by pertrai1** [comment]
Ah, did not know that we had agreed on when they would start or not. I was under the impression that is what pull requests are for. No point in pull requests unless they are reviewed. Otherwise, just commit straight to the develop or master branch.

**Pull request merged**
