### PR TITLE
Retain ballot scroll #455

### PR DESCRIPTION
**Pull request by Anoninnyc**
### What github.com/wevote/WebApp/issues does this fix?
Enables retention of ballot scroll, as outlined in @DaleMcGrew #455 example 
### Changes included this pull request?
Integrate ["react-router-scroll"](https://www.npmjs.com/package/react-router-scroll) package

### CODE REVIEW

**Comment by Anoninnyc** [comment]
Is this a problem with our (non-existent(?)) test, or my code?

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc I'm not sure why the continuous-integration error happened, but I'm cc'ing @pertrai1 in case he has any ideas.

I am testing this on my local machine, and in package.json I had to move "history": "^4.5.1" up from devDependencies to dependencies in order for "npm install" to run without errors. Then I got this error:
npm WARN EPEERINVALID react-router-scroll@0.4.1 requires a peer of history@^2.0.0 || ^3.0.0 but none was installed.

...and when I run "npm start" I get this error and the local app won't run:
Error: Cannot find module 'history/lib/DOMStateStorage' from '/Users/dalemcgrew/PythonProjects/PersonalGitForks/WebApp/node_modules/react-router-scroll/lib'

Any ideas?

**Comment by Anoninnyc** [comment]
@DaleMcGrew So, 
1. To be clear, the app and scroll is working on my machine. 
2. I did run into a similar problem with peer dependencies, though it always npm "ran".

You may have rm -rf /node_modules, then npm install. 
I'm gonna try  that now and let you know how you can replicate what I have on machine without errors being thrown.

**Comment by Anoninnyc** [comment]
@DaleMcGrew So, I just cloned my current repo into another folder on my machine. Then, I npm installed (as usual). Then, I copied the server config (as usual). The I ran npm run start. No errors, and my scroll update is working. 

I did get a *warning* of "react-router-scroll@0.4.1 requires a peer of history@^2.0.0 || ^3.0.0 but none was installed.", but everything is running fine.

Sees likely that this is an npm error. Are you able to remove the /node_modules, clear the npm cache, then reinstall?

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, I did these two commands:
rm -rf node_modules/
npm cache clean

In a virtual environment built for WebApp, and I get the same "Error: Cannot find module 'history/lib/DOMStateStorage' from '/Users/dalemcgrew/PythonProjects/PersonalGitForks/WebApp/node_modules/react-router-scroll/lib'"

After running "npm install" a few times, the only remaining warning is:
npm WARN EPEERINVALID react-router-scroll@0.4.1 requires a peer of history@^2.0.0 || ^3.0.0 but none was installed.

I wonder if react-router-scroll@0.4.1 is not compatible with history version 4.5.1?

**Comment by DaleMcGrew** [comment]
Hello @Anoninnyc I backed off the history version to 3.0.0 and it seems to work now! It looks like we have a solution. Thank you!

**Comment by Anoninnyc** [comment]
@DaleMcGrew OK- sounds good...

**Comment by DaleMcGrew** [comment]
👍

**Pull request merged**
