### PR TITLE
remove duplicated jquery loading

### PR DESCRIPTION
**Pull request by lisamcho**
Here's another thing that will reduce loading time.
jQuery was being loaded in the vendor files (which I think will get compiled to bundle.js), AND loaded via CDN. Removing it from vendor files greatly reduces size of bundle.js

### CODE REVIEW

**Comment by DaleMcGrew** [comment]
Great find @lisamcho! @nf071590 or @pertrai1 do you see any issues with removing jQuery from the bundle?

**Comment by nf071590** [comment]
I also noticed this. We need to rereference dependencies in the app after its removed from the bundle.

**Comment by DaleMcGrew** [comment]
@nf071590 Should we re-reference dependencies in the app prior to approving this pull request?

**Comment by nf071590** [comment]
It looks like @lisamcho did this.

**Comment by DaleMcGrew** [comment]
Cool, thank you @nf071590 👍

**Comment by nf071590** [comment]
Test to make sure all the Ajax requests still work and it can be merged.

**Comment by lisamcho** [comment]
OK, I see a thumbsup so I'm merging.

**Comment by pertrai1** [comment]
@lisamcho great catch. @DaleMcGrew it is a good time now to get our static files being requested from our S3 bucket so we can test the round trip requests. We would also need to implement the CI process when files our put into the S3 bucket. We will probably be using the eastern region of Amazon for an S3 bucket.

@nf071590 @josephevans - I have a preference of hosting our own vendor files instead of CDN versions. Agree or disagree? We can move this to an issue if need be.

Thank you for finding @lisamcho

**Pull request merged**
